services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root  # Define a senha do usuário root
      MYSQL_DATABASE: rh           # Cria o banco de dados 'rh'
      # Remover as linhas a seguir
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  db_data:

